### ISSUE TITLE
Deserialization validation logic repeats queries

### ISSUE THREAD

**Issue by bjester** [learningequality/morango#111]
## Background
Deserialization can be a lengthy process.

## Observed behavior
It appears that there are a significant number of repeated and unnecessary database queries that occur while validating 
 and deserializing transferred data.

## Desired behavior
Validation logic should be optimized such that it shouldn't produce repeated queries, thereby ensuring that Morango operations execute as swiftly as possible.

**Comment by jamalex** [comment]
The repeated queries look to be a result of the way Django does model validation, specifically for foreign keys.

- When we deserialize a block of records from the Morango Store into the app models, we run `validate` on them to ensure the data is valid, before (bulk) saving them.
- If the model has a foreign key, Django then fires off a query to ensure the existence of the target record.
- If, for example, we're deserializing hundreds of log records that all foreign key to the same user, we're then firing off hundreds of identical queries (one per log record), even though we're inside a "SERIALIZABLE" (read-isolated) transaction and there's no way the existence of the user could have changed between the queries.

We still do want to carry out foreign key referential integrity checks, but we want to do so as efficiently as possible. Some options may include:
1. Looping over the block of records and building a list of target models to check existence for, then doing these existence checks as one large query.
2. Caching (within the scope of the deserialization task) the results of a specific foreign key lookup so we at least don't re-run the same query it if has already been cached.

Doing either of the approaches above will likely require overriding some of the native Django validation methods (noting that we still do want to do other types of non-foreignkey validation checks as well, so we can't just replace the built-in validation completely). Option 2 seems like it may be simpler, but Option 1 may be more efficient.

To start with, we'd want a test case that ensures:
- A record with an actual broken foreign key doesn't prevent deserialization of the rest, and it stays in the Store marked as "dirty".
- During deserialization, we don't run the same validation query (with the same values) multiple times.
- All the valid records are still deserialized.
