### ISSUE TITLE
`last_activity_timestamp` values aren't updated on session activity

### ISSUE THREAD

**Issue by jamalex** [learningequality/morango#119]
We set this field on the `SyncSession` and `TransferSession` when they're first created ([here](https://github.com/learningequality/morango/blob/380cab228a72a0ac6a20926ae6963cb76054b9e1/morango/sync/syncsession.py#L197) and [here](https://github.com/learningequality/morango/blob/380cab228a72a0ac6a20926ae6963cb76054b9e1/morango/sync/syncsession.py#L545)), but I can't find anywhere that they get updated as a side-effect of ongoing activity within the sessions.

This is corroborated by this KDP data that shows the start and last activity timestamps being near identical across the board:
```
>>> while True: ss = SyncSession.objects.order_by("?")[0]; ts = ss.transfersession_set.first(); ts.last_activity_timestamp - ts.start_timestamp
datetime.timedelta(microseconds=11)
datetime.timedelta(microseconds=54)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=6)
datetime.timedelta(microseconds=29)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=9)
datetime.timedelta(microseconds=9)
datetime.timedelta(microseconds=6)
datetime.timedelta(microseconds=11)
datetime.timedelta(microseconds=9)
datetime.timedelta(microseconds=8)
datetime.timedelta(microseconds=6)
datetime.timedelta(microseconds=9)
datetime.timedelta(microseconds=7)
datetime.timedelta(microseconds=9)
datetime.timedelta(microseconds=14)
[...]
```

This field isn't currently being actively referenced anywhere in code, so it's not a critical issue at the moment, but this will become more important once the garbage collection code comes in (soon), so I wanted to make sure we tracked this.

**Comment by bjester** [comment]
Resolved by https://github.com/learningequality/morango/pull/125
