### ISSUE TITLE
Add custom user-agent to requests

### ISSUE THREAD

**Issue by bjester** [learningequality/morango#191]
## Observed behavior

The user agent for API calls made with python `requests` do not clearly identify the device as Morango

## Errors and logs

Perhaps connected with errors like the following although these are not the primary reason to customize the user-agent:
```
http.client.RemoteDisconnected: Remote end closed connection without response
```

## Expected behavior

It's recommended that we clearly identify the application making API calls, to differentiate it from potential scripting. According to MDN, it should have the format:
```
User-Agent: <product> / <product-version> <comment>
```
Ideally it should use the `MORANGO_INSTANCE_INFO` to append the application information with which Morango is integrated with. So for example, with Kolibri 0.16.0:
```
User-Agent: morango/0.6.17 kolibri/0.16.0 python-requests/2.28.2
```

## User-facing consequences

Web application firewalls may take more aggressive action against clients making many requests if it appears to be purely something scripted.

## Context

Morango 0.6+

**Comment by vkWeb** [comment]
Closing as fixed in https://github.com/learningequality/morango/pull/197

**Comment by vkWeb** [comment]
Ohh looks like I cannot close this issue, I might not have write permissions on morango. @bjester this can be safely closed.
