### ISSUE TITLE
Allow bypassing of running process check

### ISSUE THREAD

**Issue by bjester** [learningequality/morango#193]
## Overview 
With the ability to resume syncs, we integrated a mechanism that checks whether the process ID it previously ran within is still running. If the sync is initiated by the CLI, this mechanism makes sense. Although, with automated workflows, like a sync processing through a task worker process, it would run into this check if picked up by the same worker process again

#### Description and outcomes
Add an option to the `resume_sync_session` method which bypasses this check:
https://github.com/learningequality/morango/blob/7e8fae5298d028da25c47fce6723d79a7a0a3de1/morango/sync/syncsession.py#L283-L290

**Comment by roy-ketan** [comment]
@bjester can i work on it, if it is not allotted to anyone

**Comment by bjester** [comment]
Hi @roy-ketan,

Thank you for your interest! This issue is already assigned and has an open PR. Our other projects [Kolibri](https://github.com/learningequality/kolibri) and [Kolibri Studio](https://github.com/learningequality/studio) are great places to look for contributor friendly issues.

**Comment by bjester** [comment]
Closed by https://github.com/learningequality/morango/pull/194
