### ISSUE TITLE
tag and publish release

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/morango#34]
this is a pre-requisite to updating Kolibri's requirements

**Comment by benjaoming** [comment]
@ralphiee22 just want to flag that this is a real issue! I don't know which commits you've released to PyPi and thus it's hard to reproduce issues that are released in Kolibri and get them fixed... I can scavenge around to check when you bumped the version number, but that's not a final proof. I can also download the code and see which commit it matches. But a tag is and must be added when something is released.

**Comment by indirectlylit** [comment]
Looks like nothing is consistent here:

* `__init__.py` says `__version__ = "0.2.3"`
* `pypi` and Kolibri say 0.2.4
* tags say nothing
* milestone says 0.2.0

Not too much has happened in git, so I think it's a safe assumption that the current head of master is the latest release, and that release is called 0.2.4. Everything else should be updated to conform.

@ralphiee22 is out now, so I'll take this on if that sounds right to you @benjaoming ?

**Comment by indirectlylit** [comment]
oh no, that's not correct - didn't notice that @benjaoming's commits might be more recent

**Comment by benjaoming** [comment]
@indirectlylit I updated the milestone

In the absence of @ralphiee22 I will do some digging, get the tags added and ship the fixed morango (I have PyPi access)

**Comment by ralphiee22** [comment]
All versions of morango on pypi are now tagged in github, and we will continue to tag releases with release notes/changes.

**Comment by indirectlylit** [comment]
more tags than a going-out-of-business sale

![image](https://user-images.githubusercontent.com/2367265/36149412-6a220604-1074-11e8-8189-357802e25d24.png)

**Comment by indirectlylit** [comment]
thanks!
