### ISSUE TITLE
Morango's dependency versions are not consistent with Kolibri's dependency version

### ISSUE THREAD

**Issue by lyw07** [learningequality/morango#52]
After Travis CI upgrades the pip version to 10.0.0, it finds an issue below when running `pip install -r requirements.txt` for `kolibri`:
```
morango 0.2.4 has requirement django-mptt<0.9,>=0.8.0, but you'll have django-mptt 0.9.0 which is incompatible.
morango 0.2.4 has requirement djangorestframework<3.7,>=3.3.3, but you'll have djangorestframework 3.7.7 which is incompatible.
```

`morango` still gets downloaded successfully, but I think it might be better if we can get rid of these warnings?

Reference: https://travis-ci.org/learningequality/kolibri/jobs/366953009#L774

**Comment by ralphiee22** [comment]
I am currently working on this!

**Comment by ralphiee22** [comment]
Solved in https://github.com/learningequality/morango/pull/51/files.
Will release new version and update in this PR https://github.com/learningequality/kolibri/pull/2948.
