### ISSUE TITLE
SQLite-based?

### ISSUE THREAD

**Issue by benjaoming** [learningequality/morango#54]
Hi @ralphiee22 and @jamalex 

I was wondering if the description of this project is attempting to rule out other db backends or it's just a temporary scoping?

**Comment by ralphiee22** [comment]
We support postgres as a backend as well now.

**Comment by benjaoming** [comment]
Yay :tada:

**Comment by benjaoming** [comment]
@ralphiee22 

![image](https://user-images.githubusercontent.com/374612/58589726-d1379f00-8262-11e9-89c9-850cd73a984a.png)

**Comment by benjaoming** [comment]
@ralphiee22 

![Uploading image.png…]()
