### ISSUE TITLE
Don't set dirty bit when only updating MPTT fields (which aren't serialized)

### ISSUE THREAD

**Issue by jamalex** [learningequality/morango#6]
By default, when we do a save/update on a syncable model, we set the dirty bit. When a node in an MPTT tree is moved, django-mptt often [updates the MPTT fields (left/right/level/tree_id)](https://github.com/django-mptt/django-mptt/blob/8bcbe20984fcdcb85dabb6588bf0c423ff1209bf/mptt/managers.py#L690) for a number of other nodes as well. Since we'll be excluding these MPTT fields from serialization/syncing, there's no need to set the dirty bit.

The easiest way to do this looks like it would be overriding [`_mptt_update`](https://github.com/django-mptt/django-mptt/blob/8bcbe20984fcdcb85dabb6588bf0c423ff1209bf/mptt/managers.py#L413) and adding the flag to not set the dirty bit (the `None`) option, on our `SyncableMPTTTreeManager` or whatever we're calling it.

**Comment by ralphiee22** [comment]
Addressed here https://github.com/learningequality/morango/commit/42539300d9975304af7de687d80b2d3b3815a79c#diff-f77b89baf05d84f7905d74829f29497eR15
