### ISSUE TITLE
"Project description" section on PyPi is not formatted correctly

### ISSUE THREAD

**Issue by jonboiser** [learningequality/morango#74]
At https://pypi.org/project/morango/0.4.7/, the "Project description" is showing un-parsed markdown, instead of formatted text. The main cause seemed to be out-of-date build dependencies.

A workaround was to forgo using the Markdown README and hard-code RST-formatted string in learningequality/kolibri#5687

**Comment by ralphiee22** [comment]
seems to be partly resolved in https://pypi.org/project/morango/0.4.8/?

**Comment by benjaoming** [comment]
Yup, works great!
